version: '3'

services:

  api:
    build:
      context: ./full_api
      dockerfile: Dockerfile
    volumes:
      - .:/code
    environment:
      GUNICORN_RELOAD: "False"
      LOG_LOCAL: "True" # Desabilita logging externo de IP, id
      LOGGER_SWAGGER: "False" # Desabilita logging para /docs /favicon etc
      # Apenas para uvicorn
      LC_ALL: "C.UTF-8"
      LANG: "C.UTF-8"
      FASTAPI_RELOAD: "True"
    command: /bin/sh ./run.sh # Uvicorn sh - funciona reload
    # command: ["python3", "-m", "full_api.api"] # Uvicorn python
    ports:
      - 8080:8080
    networks:
      - backend

  mongodb:
    container_name: full_api.api-mongodb
    image: mongo
    restart: unless-stopped
    volumes:
      - full_api.api-mongodb_volume:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: toor
    ports:
      - 27017:27017
    networks:
      - backend 
    # Supressão de log
    logging:
      driver: "none"
  
  mongo-express:
    container_name: full_api.api-mongo_express
    image: mongo-express
    restart: unless-stopped
    ports:
      - 8081:8081
    networks:
      - backend 
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: toor
    depends_on:
      - mongodb
    # Supressão de log  
    logging:
      driver: "none"

networks:
  backend:
    driver: bridge
volumes:
  full_api.api-mongodb_volume: