version: '3'

services:

  api:
    build:
      context: ./project
      dockerfile: Dockerfile
    volumes:
      - ./project:/code
    environment:
      GUNICORN_RELOAD: "False"
      LOG_LOCAL: "True" # Desabilita logging externo de IP, id
      LOGGER_SWAGGER: "False" # Desabilita logging para /docs /favicon etc
      FASTAPI_ROOT_PATH: ""
      # Apenas para uvicorn
      LC_ALL: "C.UTF-8"
      LANG: "C.UTF-8"
      FASTAPI_RELOAD: "True"
    command: /bin/sh run_uvicorn.sh # Uvicorn sh - funciona reload
    # command: ["python3", "-m", "api"] # Uvicorn python
    ports:
      - 8080:8080
    networks:
      - backend

  mongodb:
    container_name: project.api-mongodb
    image: mongo
    restart: unless-stopped
    volumes:
      - project.api-mongodb_volume:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: toor
    ports:
      - 27017:27017
    networks:
      - backend 
    # Supressão de log
    logging:
      driver: "none"
  
  mongo-express:
    container_name: project.api-mongo_express
    image: mongo-express
    restart: unless-stopped
    ports:
      - 8081:8081
    networks:
      - backend 
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: toor
    depends_on:
      - mongodb
    # Supressão de log  
    logging:
      driver: "none"

networks:
  backend:
    driver: bridge
volumes:
  project.api-mongodb_volume: